"""Generate sample transactions and run them through the ingestion pipeline.

Useful for demos and integration tests; not for production data flow.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Tuple

from src.domain.authorization import Principal, Role
from src.domain.entities.wallet import WalletManager
from src.infrastructure.persistence.sqlite import AlertRepository, TransactionIndexRepository
from src.service.transaction_ingestion_service import TransactionIngestionService
from src.utils.data_generator import DataGenerator

logger = logging.getLogger("blockchain_audit")


class DemoService:
    def __init__(
        self,
        wallet_manager: WalletManager,
        ingestion: TransactionIngestionService,
        alerts: AlertRepository,
        transactions: TransactionIndexRepository,
    ):
        self._wallets = wallet_manager
        self._ingestion = ingestion
        self._alerts = alerts
        self._transactions = transactions

    def generate(self, principal: Principal, payload: Dict[str, Any]) -> Tuple[dict, str]:
        principal.require(Role.ADMIN, Role.OPERATOR)

        count = max(1, min(int(payload.get("count", 50)), 500))
        include_anomalies = bool(payload.get("include_anomalies", True))
        anomaly_ratio = float(payload.get("anomaly_ratio", 0.10 if include_anomalies else 0.0))

        generator = DataGenerator(self._wallets)
        transactions = generator.generate_normal_transactions(count)

        if include_anomalies:
            anomaly_count = max(1, min(count // 2, int(round(count * anomaly_ratio))))
            transactions.extend(generator.generate_anomalies(anomaly_count))

        ordered = sorted(transactions, key=lambda tx: tx.timestamp)

        anomalies_detected = flagged_count = invalid_signature_count = 0

        for tx in ordered:
            report = self._ingestion.add_transaction(tx)
            status = "REJECTED"
            if report.signature_valid:
                status = "FLAGGED" if report.flagged_for_review else "PENDING"
            self._transactions.index(
                tx,
                block_index=None,
                tx_status=status,
                is_flagged=report.flagged_for_review,
                ml_score=float(report.anomaly_result.anomaly_score) if report.anomaly_result else None,
                ml_reason=report.anomaly_result.explanation if report.anomaly_result else None,
            )

            if report.is_suspicious:
                anomalies_detected += 1
                if report.flagged_for_review:
                    flagged_count += 1
                if not report.signature_valid:
                    invalid_signature_count += 1
                self._alerts.save(report)

        logger.info(
            "Demo data generated by %s: %s transaction(s), %s suspicious, %s flagged, %s invalid-signature",
            principal.username,
            len(ordered),
            anomalies_detected,
            flagged_count,
            invalid_signature_count,
        )

        return {
            "generated": len(ordered),
            "anomalies_detected": anomalies_detected,
            "flagged": flagged_count,
            "invalid_signatures": invalid_signature_count,
        }, f"{len(ordered)} transactions generated ({flagged_count} flagged for review)"
