"""Anomaly controller routes."""

from __future__ import annotations

import logging
from typing import Any, Dict, Tuple

from flask import Blueprint, request
from flask_jwt_extended import get_jwt, get_jwt_identity, jwt_required

from ..app_context import get_app_ctx
from ..rate_limit import rate_limit
from ..responses import api_error, api_success, get_pagination_params

logger = logging.getLogger("blockchain_audit")

anomaly_bp = Blueprint("anomaly", __name__, url_prefix="/api")

ALLOWED_TRAINING_MODES = {"blockchain", "synthetic"}


def _require_operator_or_admin() -> Tuple[bool, Any]:
    claims = get_jwt()
    if claims.get("role") not in ("admin", "operator"):
        return False, api_error("Access forbidden. Required: admin, operator", 403, error_code="FORBIDDEN")
    return True, None


@anomaly_bp.route("/anomaly/train", methods=["POST"])
@rate_limit(limit=10, window_seconds=60, scope='anomaly_train')
@jwt_required()
def train_detector():
    app_ctx = get_app_ctx()
    allowed, response = _require_operator_or_admin()
    if not allowed:
        return response

    payload: Dict[str, Any] = request.get_json(silent=True) or {}
    mode = str(payload.get("mode") or ("synthetic" if payload.get("use_synthetic") else "blockchain")).lower()
    if mode not in ALLOWED_TRAINING_MODES:
        return api_error("Invalid training mode. Use 'blockchain' or 'synthetic'.", 400, error_code="INVALID_MODE")

    try:
        result = app_ctx.anomaly_service.train_detector(mode=mode, sample_count=int(payload.get('sample_count', 800)))
        return api_success(
            data={k: v for k, v in result.items() if k != 'message'},
            message=result['message'],
        )
    except ValueError as exc:
        return api_error(str(exc), 400, error_code="INSUFFICIENT_DATA")
    except Exception as exc:  # noqa: BLE001
        logger.exception("Error training detector")
        return api_error(f"Training error: {exc}", 500, error_code="TRAINING_ERROR")


@anomaly_bp.route("/anomaly/stats", methods=["GET"])
@jwt_required()
def get_anomaly_stats():
    app_ctx = get_app_ctx()
    return api_success(data=app_ctx.anomaly_service.get_anomaly_stats())


@anomaly_bp.route("/alerts", methods=["GET"])
@jwt_required()
def get_alerts():
    app_ctx = get_app_ctx()
    page, per_page = get_pagination_params()
    severity = request.args.get("severity")
    resolved_param = request.args.get("resolved")

    is_resolved = None
    if resolved_param is not None:
        is_resolved = resolved_param.lower() in ("true", "1", "yes")

    alerts, total = app_ctx.anomaly_service.get_alerts(
        page=page,
        per_page=per_page,
        severity=severity,
        is_resolved=is_resolved,
    )
    pagination = {
        "page": page,
        "per_page": per_page,
        "total": total,
        "total_pages": max(1, (total + per_page - 1) // per_page),
        "has_next": page * per_page < total,
        "has_prev": page > 1,
    }
    return api_success(data={"alerts": alerts, "count": len(alerts)}, pagination=pagination)


@anomaly_bp.route("/alerts/<int:alert_id>/resolve", methods=["PUT"])
@jwt_required()
def resolve_alert(alert_id: int):
    app_ctx = get_app_ctx()
    allowed, response = _require_operator_or_admin()
    if not allowed:
        return response

    resolved = app_ctx.anomaly_service.resolve_alert(alert_id, get_jwt_identity())
    if resolved:
        logger.info("Alert #%s resolved by %s", alert_id, get_jwt_identity())
        return api_success(message=f"Alert #{alert_id} marked as resolved")
    return api_error(f"Alert #{alert_id} not found or already resolved", 404, error_code="ALERT_NOT_FOUND")


@anomaly_bp.route("/demo/generate", methods=["POST"])
@jwt_required()
def generate_demo_data():
    app_ctx = get_app_ctx()
    payload = request.get_json(silent=True) or {}
    count = max(1, min(int(payload.get("count", 50)), 500))
    include_anomalies = bool(payload.get("include_anomalies", True))
    anomaly_ratio = float(payload.get("anomaly_ratio", 0.10 if include_anomalies else 0.0))

    result = app_ctx.anomaly_service.generate_demo_data(count, include_anomalies, anomaly_ratio)

    logger.info(
        "Demo data generated by %s: %s transaction(s), %s suspicious, %s flagged, %s invalid-signature",
        get_jwt_identity(),
        result['generated'],
        result['anomalies_detected'],
        result['flagged'],
        result['invalid_signatures'],
    )

    return api_success(
        data=result,
        message=f"{result['generated']} transactions generated ({result['flagged']} flagged for review)",
    )
